version: '3'

services:
    nginx:
        container_name: ${APP_NAME}.nginx
        build: ./nginx
        ports:
            - ${SERVER_PORT}:80
            - 443:443
        links: 
            - php
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log:/var/log/nginx
            - ./code:/var/www
        
    php:
        container_name: ${APP_NAME}.php
        build: ./php
        volumes: 
            - ./code:/var/www
        links: 
            - database
           
    database:
        container_name: ${APP_NAME}.database
        image: mysql:5.7
        environment: 
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_USER}
        ports:
            - 3306:3306  
        volumes:
            - dbdata:/var/lib/mysql
volumes: 
  dbdata:
    
    